# total major tom deployment setup
version: "3.7"
services:
  api:
    build: ./
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - type: bind
        source: ../majortom.yml
        target: /majortom.yml
  shiny:
    build: 
      dockerfile: Dockerfile.shiny
      context: ./
    restart: always
    ports:
      - "127.0.0.1:5777:5777"

